### ISSUE TITLE
The folder needs to be renamed to end with .lrplugin to work.

### ISSUE THREAD

**Issue by Waitwutmyname** [ftischhauser/JPEGOptimizer#1]
The folder needs to end in .lrplugin to work. It should be entirely renamed JPEGOptimizer-master.lrplugin
This confused me at first, and I don't see a reason not to name it with the extension from the start.

**Comment by ftischhauser** [comment]
The recommended distribution are the official releases which also include the necessary binary files, the plugin folder is named correctly in there.
